version: "~> 1.0"

language: go

os:
  - linux
  - osx
arch:
  - amd64
  - arm64
go:
  - 1.15.x
  - 1.14.x
  - 1.13.x

env:
  global:
    - GO111MODULE=on

dist: bionic
go_import_path: kreklow.us/go/t38c
script: go test -v -race ./...

jobs:
  include:
    - name: "Test Coverage"
      stage: validate
      script: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
      after_success: bash <(curl -s https://codecov.io/bash)
