name: PR Checks
on: [pull_request]

jobs:
  pr-run:
    runs-on: ubuntu-latest
    name: GolangCI-Lint
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.19.0'
      - name: Run Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.49
      - name: Run Tests
        run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
      - name: Upload to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.txt
