name: Test
on: [push]

env:
  GO111MODULE: on

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '~1.15.0', '~1.14.0', '~1.13.0' ]
    name: Go ${{ matrix.go }}
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Tests
        run: go test -v -race ./...
  codecov:
    needs: test
    runs-on: ubuntu-latest
    name: Codecov
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '~1.15.0'
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Tests
        run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
      - name: Upload to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.txt
